<?php

return [
    'default_entries' => [
        [
            'key'         => 'products',
            'sort'        => 1,
            'active'      => true,
            'keywords'    => ['product', 'loan', 'bidhaa', 'mkopo', 'offer'],
            'question_en' => 'What loan products do you offer?',
            'question_sw' => 'Mnatoa mikopo gani?',
            'answer_en'   => 'We offer individual, business, group, asset-backed, education and emergency loans. Browse all products on our Products page or tell me what you need.',
            'answer_sw'   => 'Tunatoa mikopo ya binafsi, biashara, vikundi, mali, elimu na dharura. Vinjari bidhaa zote kwenye ukurasa wa Bidhaa.',
        ],
        [
            'key'         => 'apply',
            'sort'        => 2,
            'active'      => true,
            'keywords'    => ['apply', 'application', 'register', 'sign up', 'omb', 'jisajili'],
            'question_en' => 'How do I apply for a loan?',
            'question_sw' => 'Ninaomba mkopo vipi?',
            'answer_en'   => 'To apply, register or log in, choose a product, and complete our guided application wizard. Most applications take under 15 minutes.',
            'answer_sw'   => 'Kuomba, jisajili au ingia, chagua bidhaa, na kamilisha mwongozo wetu. Maombi mengi huchukua chini ya dakika 15.',
        ],
        [
            'key'         => 'marketplace',
            'sort'        => 3,
            'active'      => true,
            'keywords'    => ['market', 'asset', 'vehicle', 'mali', 'soko', 'gari'],
            'question_en' => 'Tell me about the asset marketplace',
            'question_sw' => 'Niambie kuhusu soko la mali',
            'answer_en'   => 'Our Asset Marketplace lets you finance vehicles and equipment with transparent deposits and weekly instalments.',
            'answer_sw'   => 'Soko letu la mali linakuruhusu kupata magari na vifaa kwa amana na malipo ya kila wiki.',
        ],
        [
            'key'         => 'repayment',
            'sort'        => 4,
            'active'      => true,
            'keywords'    => ['repay', 'payment', 'malipo', 'lipa', 'installment'],
            'question_en' => 'How do repayments work?',
            'question_sw' => 'Malipo yanafanywaje?',
            'answer_en'   => 'Repayments can be made from your borrower dashboard under Payments. Your schedule is available under Loans.',
            'answer_sw'   => 'Malipo yanaweza kufanywa kutoka dashibodi yako chini ya Malipo.',
        ],
        [
            'key'         => 'membership',
            'sort'        => 5,
            'active'      => true,
            'keywords'    => ['member', 'membership', 'uanachama', 'fee'],
            'question_en' => 'What is the membership fee?',
            'question_sw' => 'Ada ya uanachama ni kipi?',
            'answer_en'   => 'Membership is valid for one year. Pay the registration fee once, then renew before expiry to keep applying for loans.',
            'answer_sw'   => 'Uanachama ni halali kwa mwaka mmoja. Lipa ada ya usajili mara moja, kisha fanya upya kabla ya kuisha.',
        ],
        [
            'key'         => 'affiliate',
            'sort'        => 6,
            'active'      => true,
            'keywords'    => ['affiliate', 'commission', 'refer', 'msambazaji'],
            'question_en' => 'How does the affiliate programme work?',
            'question_sw' => 'Programu ya wasambazaji inafanyaje kazi?',
            'answer_en'   => 'Our affiliate programme pays commission for referred borrowers. Visit the Affiliates page to apply.',
            'answer_sw'   => 'Programu yetu ya wasambazaji inalipa kamisheni kwa wateja uliowaelekeza.',
        ],
        [
            'key'         => 'contact',
            'sort'        => 7,
            'active'      => true,
            'keywords'    => ['contact', 'support', 'human', 'wasiliana', 'msaada', 'help'],
            'question_en' => 'I need to speak to someone',
            'question_sw' => 'Nahitaji kuongea na mtu',
            'answer_en'   => 'You can reach us by phone, email, or WhatsApp. Visit our Support center or send feedback through the feedback form.',
            'answer_sw'   => 'Unaweza kuwasiliana nasi kwa simu, barua pepe, au WhatsApp. Tembelea Kituo cha msaada au tuma maoni.',
        ],
        [
            'key'         => 'faq_what_is',
            'sort'        => 8,
            'active'      => true,
            'keywords'    => ['what is', 'kopafasta', 'nini', 'platform'],
            'question_en' => 'What is Kopafasta?',
            'question_sw' => 'Kopafasta ni nini?',
            'answer_en'   => 'Kopafasta is a mobile-first microfinance platform offering transparent loans, asset financing, and investment opportunities in Tanzania.',
            'answer_sw'   => 'Kopafasta ni jukwaa la mikopo ya simu linalotoa mikopo wazi, ufadhili wa mali, na fursa za uwekezaji nchini Tanzania.',
        ],
        [
            'key'         => 'faq_disbursement',
            'sort'        => 9,
            'active'      => true,
            'keywords'    => ['disburse', 'disbursement', 'how fast', 'malipo ya mkopo', 'pesa'],
            'question_en' => 'How fast is disbursement?',
            'question_sw' => 'Mkopo unatolewa kwa haraka kiasi gani?',
            'answer_en'   => 'Most approved loans are disbursed within a few hours of approval, during business hours. Emergency loans may be faster.',
            'answer_sw'   => 'Mikopo mingi inayoidhinishwa hutolewa ndani ya masaa michache wakati wa saa za kazi.',
        ],
        [
            'key'         => 'faq_documents',
            'sort'        => 10,
            'active'      => true,
            'keywords'    => ['document', 'nida', 'papers', 'hati', 'identity'],
            'question_en' => 'What documents do I need?',
            'question_sw' => 'Nahitaji hati gani?',
            'answer_en'   => 'Your NIDA, a working phone, and proof of income or business. Larger loans may require collateral or guarantors.',
            'answer_sw'   => 'NIDA yako, simu inayofanya kazi, na uthibitisho wa kipato au biashara. Mikopo mikubwa inaweza kuhitaji dhamana au wadhamini.',
        ],
        [
            'key'         => 'faq_pin',
            'sort'        => 11,
            'active'      => true,
            'keywords'    => ['pin', 'reset', 'forgot', 'nenosiri', 'otp'],
            'question_en' => 'How do I reset my PIN?',
            'question_sw' => 'Ninawezaje kubadilisha PIN yangu?',
            'answer_en'   => 'Use the Forgot PIN link on the login page. We will send an OTP to your registered phone number.',
            'answer_sw'   => 'Tumia kiungo cha Umesahau PIN kwenye ukurasa wa kuingia. Tutatuma OTP kwenye nambari yako iliyosajiliwa.',
        ],
        [
            'key'         => 'faq_guarantor',
            'sort'        => 12,
            'active'      => true,
            'keywords'    => ['guarantor', 'mdhamini', 'sponsor'],
            'question_en' => 'Do I need guarantors?',
            'question_sw' => 'Nahitaji wadhamini?',
            'answer_en'   => 'Some products require guarantors. You will be prompted during the loan application if your selected product needs them.',
            'answer_sw'   => 'Bidhaa zingine zinahitaji wadhamini. Utaombwa wakati wa maombi ya mkopo ikiwa bidhaa yako inahitaji.',
        ],
    ],
];
