<?php

return [
    'default_entries' => [
        [
            'key'      => 'products',
            'sort'     => 1,
            'active'   => true,
            'keywords' => ['product', 'loan', 'bidhaa', 'mkopo', 'offer'],
            'question_en' => 'What loan products do you offer?',
            'question_sw' => 'Mnatoa bidhaa gani za mkopo?',
            'answer_en'   => 'We offer individual, business, group, asset-backed, education and emergency loans. Browse all products on our Products page or tell me what you need.',
            'answer_sw'   => 'Tunatoa mikopo ya mtu binafsi, biashara, vikundi, mali, elimu na dharura. Tembelea ukurasa wa Bidhaa kuona zote.',
        ],
        [
            'key'      => 'apply',
            'sort'     => 2,
            'active'   => true,
            'keywords' => ['apply', 'register', 'omb', 'jiandikishe', 'sign up'],
            'question_en' => 'How do I apply for a loan?',
            'question_sw' => 'Nawezaje kuomba mkopo?',
            'answer_en'   => 'Register or log in, choose a product, and complete our guided application wizard. Most applications take under 15 minutes.',
            'answer_sw'   => 'Jisajili au ingia, chagua bidhaa, na kamilisha ombi letu la hatua kwa hatua.',
        ],
        [
            'key'      => 'marketplace',
            'sort'     => 3,
            'active'   => true,
            'keywords' => ['market', 'asset', 'mali', 'vehicle', 'gari'],
            'question_en' => 'Tell me about the asset marketplace',
            'question_sw' => 'Niambie kuhusu soko la mali',
            'answer_en'   => 'Our Asset Marketplace lets you finance vehicles and equipment with transparent deposits and weekly instalments.',
            'answer_sw'   => 'Soko letu la mali linakuwezesha kufadhili magari na vifaa kwa amana na malipo ya kila wiki.',
        ],
        [
            'key'      => 'repayment',
            'sort'     => 4,
            'active'   => true,
            'keywords' => ['repay', 'payment', 'malipo', 'installment'],
            'question_en' => 'How do repayments work?',
            'question_sw' => 'Malipo yanafanyaje kazi?',
            'answer_en'   => 'Repayments can be made from your borrower dashboard under Payments. Your schedule is available under Loans.',
            'answer_sw'   => 'Malipo yanaweza kufanywa kutoka dashibodi yako chini ya Malipo. Ratiba iko chini ya Mikopo.',
        ],
        [
            'key'      => 'membership',
            'sort'     => 5,
            'active'   => true,
            'keywords' => ['member', 'uanachama', 'registration fee'],
            'question_en' => 'How does membership work?',
            'question_sw' => 'Uanachama unafanyaje kazi?',
            'answer_en'   => 'Membership is valid for one year. Pay the registration fee once, then renew before expiry to keep applying for loans.',
            'answer_sw'   => 'Uanachama una uhalali wa mwaka mmoja. Lipa ada ya usajili mara moja, kisha fanya upyaishaji kabla ya kuisha.',
        ],
        [
            'key'      => 'affiliate',
            'sort'     => 6,
            'active'   => true,
            'keywords' => ['affiliate', 'wakala', 'commission', 'promo'],
            'question_en' => 'How does the affiliate programme work?',
            'question_sw' => 'Programu ya wakala inafanyaje kazi?',
            'answer_en'   => 'Apply on our Affiliates page. Once approved, share your referral link and earn commission on referred members and applications.',
            'answer_sw'   => 'Omba kwenye ukurasa wa Wakala. Ukishaidhinishwa, shiriki kiungo chako na upate kamisheni.',
        ],
    ],
];
