<?php

return [
    'default_entries' => [
        [
            'key' => 'products',
            'sort' => 1,
            'active' => true,
            'keywords' => ['product', 'loan', 'bidhaa', 'mkopo', 'offer', 'products'],
            'question_en' => 'What loan products do you offer?',
            'question_sw' => 'Mnatoa bidhaa gani za mkopo?',
            'answer_en' => 'Browse published products on the Products page. Amounts, rates and fees come from live product settings — ask about a product name for details, or open Products.',
            'answer_sw' => 'Angalia bidhaa zilizochapishwa kwenye ukurasa wa Bidhaa. Kiasi, viwango na ada hutoka kwenye mipangilio hai — uliza jina la bidhaa au fungua Bidhaa.',
        ],
        [
            'key' => 'apply',
            'sort' => 2,
            'active' => true,
            'keywords' => ['apply', 'register', 'omb', 'jiandikishe', 'sign up', 'application'],
            'question_en' => 'How do I apply for a loan?',
            'question_sw' => 'Nawezaje kuomba mkopo?',
            'answer_en' => 'Register or log in, choose an eligible product, and complete the guided application. Guarantor, collateral or valuation steps appear when that product requires them. We do not guarantee approval.',
            'answer_sw' => 'Jisajili au ingia, chagua bidhaa unayostahili, na kamilisha ombi la hatua kwa hatua. Mdhamini, dhamana au uthamini huonekana pale bidhaa inapohitaji. Hatuhakikishi idhini.',
        ],
        [
            'key' => 'fees',
            'sort' => 3,
            'active' => true,
            'keywords' => ['fee', 'fees', 'ada', 'application fee', 'charges'],
            'question_en' => 'What fees apply?',
            'question_sw' => 'Ada zipi zinatumika?',
            'answer_en' => 'Fees depend on the selected product and stage. Choose a loan product for the current Settings-backed summary rather than a full catalogue dump.',
            'answer_sw' => 'Ada zinategemea bidhaa na hatua. Chagua bidhaa ya mkopo kwa muhtasari wa sasa kutoka Mipangilio badala ya orodha nzima.',
        ],
        [
            'key' => 'guarantor',
            'sort' => 4,
            'active' => true,
            'keywords' => ['guarantor', 'mdhamini', 'guarantee'],
            'question_en' => 'When do I need a guarantor?',
            'question_sw' => 'Ninahitaji mdhamini lini?',
            'answer_en' => 'Some products require a guarantor based on product rules and amount. The application journey will request guarantor details when needed.',
            'answer_sw' => 'Bidhaa nyingine zinahitaji mdhamini kulingana na sheria za bidhaa na kiasi. Safari ya ombi itaomba maelezo ya mdhamini pale inapohitajika.',
        ],
        [
            'key' => 'group',
            'sort' => 5,
            'active' => true,
            'keywords' => ['group', 'kikundi', 'group loan'],
            'question_en' => 'How do group loans work?',
            'question_sw' => 'Mikopo ya vikundi inafanyaje kazi?',
            'answer_en' => 'Group loans follow the Group product setup: invite members, complete group steps, then underwriting. Details are on the Group product page.',
            'answer_sw' => 'Mikopo ya vikundi hufuata usanidi wa bidhaa ya Kikundi: alika wanachama, kamilisha hatua, kisha uchunguzi. Maelezo yapo kwenye ukurasa wa bidhaa ya Kikundi.',
        ],
        [
            'key' => 'collateral',
            'sort' => 6,
            'active' => true,
            'keywords' => ['collateral', 'dhamana', 'valuation', 'uthamini', 'security'],
            'question_en' => 'What about collateral and valuation?',
            'question_sw' => 'Je, kuhusu dhamana na uthamini?',
            'answer_en' => 'Secured products may require collateral and a valuation partner. Fees and steps are product-specific and shown in the application when applicable.',
            'answer_sw' => 'Bidhaa zenye dhamana zinaweza kuhitaji dhamana na mshirika wa uthamini. Ada na hatua hutegemea bidhaa na huonyeshwa kwenye ombi.',
        ],
        [
            'key' => 'marketplace',
            'sort' => 7,
            'active' => true,
            'keywords' => ['market', 'marketplace', 'asset', 'mali', 'vehicle', 'gari', 'soko'],
            'question_en' => 'Tell me about the Marketplace',
            'question_sw' => 'Niambie kuhusu Soko la mali',
            'answer_en' => 'Finance vehicles, equipment and more with clear financing terms and flexible instalments. Browse published assets on Marketplace — no deposit wording in the general proposition.',
            'answer_sw' => 'Pata magari, vifaa na zaidi kupitia mkopo na marejesho rafiki. Vinjari mali zilizochapishwa kwenye Soko.',
        ],
        [
            'key' => 'payments',
            'sort' => 8,
            'active' => true,
            'keywords' => ['pay', 'payment', 'malipo', 'repay', 'repayment', 'instalment'],
            'question_en' => 'How do repayments and payments work?',
            'question_sw' => 'Malipo na marejesho yanafanyaje kazi?',
            'answer_en' => 'After disbursement, repay from your borrower Payments area. Schedules live under Loans. For live payment status, sign in — the assistant cannot invent balances or payment status.',
            'answer_sw' => 'Baada ya utoaji, lipa kutoka sehemu ya Malipo ya mkopaji. Ratiba zipo chini ya Mikopo. Kwa hali ya malipo, ingia akaunti — msaidizi hawezi kubuni salio au hali ya malipo.',
        ],
        [
            'key' => 'plus',
            'sort' => 9,
            'active' => true,
            'keywords' => ['plus', 'kopafasta plus', 'money', 'business', 'goals'],
            'question_en' => 'What is Kopafasta Plus?',
            'question_sw' => 'Kopafasta Plus ni nini?',
            'answer_en' => 'Plus is an optional money and business intelligence layer (Money, Business, Goals, Reports, Offers, Rewards, Learn). Paying for Plus does not buy better loan approval or raise Grade/Trust.',
            'answer_sw' => 'Plus ni safu hiari ya uelewa wa pesa na biashara (Pesa, Biashara, Malengo, Ripoti, Ofa, Zawadi, Jifunze). Kulipia Plus hakununui idhini bora ya mkopo wala kuongeza Daraja/Uaminifu.',
        ],
        [
            'key' => 'grade',
            'sort' => 10,
            'active' => true,
            'keywords' => ['grade', 'trust', 'daraja', 'uaminifu', 'score'],
            'question_en' => 'What is Grade / financial trust?',
            'question_sw' => 'Daraja / uaminifu wa kifedha ni nini?',
            'answer_en' => 'Grade and trust reflect how you use and repay credit over time. Exact account scores need you to sign in. Plus does not purchase a higher Grade.',
            'answer_sw' => 'Daraja na uaminifu vinaonyesha jinsi unavyotumia na kulipa mkopo. Alama za akaunti zinahitaji uingie. Plus hainunui Daraja la juu.',
        ],
        [
            'key' => 'rewards',
            'sort' => 11,
            'active' => true,
            'keywords' => ['reward', 'rewards', 'points', 'zawadi', 'loyalty'],
            'question_en' => 'How do rewards work?',
            'question_sw' => 'Zawadi zinafanyaje kazi?',
            'answer_en' => 'Rewards and points follow the published Rewards page rules. Sign in to see your balance — the assistant will not invent points.',
            'answer_sw' => 'Zawadi na pointi hufuata sheria za ukurasa wa Zawadi. Ingia kuona salio lako — msaidizi hatabuni pointi.',
        ],
        [
            'key' => 'affiliate',
            'sort' => 12,
            'active' => true,
            'keywords' => ['affiliate', 'mauzo', 'commission', 'promo', 'referral', 'wakala'],
            'question_en' => 'How does the Affiliates programme work?',
            'question_sw' => 'Programu ya Mauzo inafanyaje kazi?',
            'answer_en' => 'Apply on the Affiliates page. After approval, share your referral link and earn commission on referred activity per your agreement.',
            'answer_sw' => 'Omba kwenye ukurasa wa Mauzo. Baada ya idhini, shiriki kiungo chako na upate kamisheni kulingana na makubaliano yako.',
        ],
        [
            'key' => 'partners',
            'sort' => 13,
            'active' => true,
            'keywords' => ['partner', 'mshirika', 'valuer', 'onboarding'],
            'question_en' => 'How do partners onboard?',
            'question_sw' => 'Washirika wanaanza vipi?',
            'answer_en' => 'Service partners apply through the Partners pages. Use Partner login after activation. Capital partners use a private link, not public menus.',
            'answer_sw' => 'Washirika wa huduma huomba kupitia kurasa za Washirika. Tumia Ingia ya Mshirika baada ya kuamilishwa. Washirika wa mtaji hutumia kiungo cha faragha, si menyu ya umma.',
        ],
        [
            'key' => 'login',
            'sort' => 14,
            'active' => true,
            'keywords' => ['login', 'ingia', 'pin', 'password', 'sign in', 'register'],
            'question_en' => 'How do I sign in or register?',
            'question_sw' => 'Naingiaje au kujisajili?',
            'answer_en' => 'Borrowers and partners choose account type on Login, then Phone+PIN or Email+Password. Register creates a borrower account; partners follow the partner journey.',
            'answer_sw' => 'Wakopaji na washirika huchagua aina ya akaunti kwenye Ingia, kisha Simu+PIN au Barua pepe+Nenosiri. Jisajili hutengeneza akaunti ya mkopaji; washirika hufuata safari ya mshirika.',
        ],
        [
            'key' => 'status',
            'sort' => 15,
            'active' => true,
            'keywords' => ['status', 'application status', 'pending', 'approved', 'hali'],
            'question_en' => 'What is my application or payment status?',
            'question_sw' => 'Hali yangu ya ombi au malipo ni ipi?',
            'answer_en' => 'Account-specific status requires you to sign in and open Loans or Payments. I will not invent approval, eligibility, balances or payment status.',
            'answer_sw' => 'Hali ya akaunti inahitaji uingie na ufungue Mikopo au Malipo. Sitabuni idhini, ustahiki, salio au hali ya malipo.',
        ],
        [
            'key' => 'membership',
            'sort' => 16,
            'active' => true,
            'keywords' => ['member', 'uanachama', 'registration fee'],
            'question_en' => 'How does membership work?',
            'question_sw' => 'Uanachama unafanyaje kazi?',
            'answer_en' => 'Membership is typically annual. Pay once, renew before expiry to keep applying. Exact fee amounts come from Settings on the membership/payment screens.',
            'answer_sw' => 'Uanachama kwa kawaida ni wa mwaka. Lipa mara moja, fanya upyaishaji kabla ya kuisha. Kiasi halisi cha ada hutoka Mipangilio kwenye skrini za uanachama/malipo.',
        ],
    ],
];
