<?php

/**
 * Default country profiles. Admin overrides stored in system_settings as country.{code}.* keys.
 */
return [
    'TZ' => [
        'name'               => 'Tanzania',
        'emoji'              => '🇹🇿',
        'active'             => true,
        'language'           => 'sw',
        'currency'           => 'TZS',
        'timezone'           => 'Africa/Dar_es_Salaam',
        'phone_prefix'       => '+255',
        'national_id_label'  => 'NIDA',
        'national_id_format' => 'nida_20',
        'grace_period_days'  => 2,
        'repayment_ratio'    => 0.3333,
        'crb_freshness_days' => 90,
        'kyc_freshness_days' => 90,
        'guarantor_required' => true,
        'contract_locale'    => 'sw',
    ],
    'KE' => [
        'name'               => 'Kenya',
        'emoji'              => '🇰🇪',
        'active'             => false,
        'language'           => 'sw',
        'currency'           => 'KES',
        'timezone'           => 'Africa/Nairobi',
        'phone_prefix'       => '+254',
        'national_id_label'  => 'National ID',
        'national_id_format' => 'digits_8',
        'grace_period_days'  => 2,
        'repayment_ratio'    => 0.3333,
        'crb_freshness_days' => 90,
        'kyc_freshness_days' => 90,
        'guarantor_required' => true,
        'contract_locale'    => 'sw',
    ],
    'UG' => [
        'name'               => 'Uganda',
        'emoji'              => '🇺🇬',
        'active'             => false,
        'language'           => 'en',
        'currency'           => 'UGX',
        'timezone'           => 'Africa/Kampala',
        'phone_prefix'       => '+256',
        'national_id_label'  => 'NIN',
        'national_id_format' => 'alphanumeric',
        'grace_period_days'  => 2,
        'repayment_ratio'    => 0.3333,
        'crb_freshness_days' => 90,
        'kyc_freshness_days' => 90,
        'guarantor_required' => true,
        'contract_locale'    => 'en',
    ],
    'RW' => [
        'name'               => 'Rwanda',
        'emoji'              => '🇷🇼',
        'active'             => false,
        'language'           => 'en',
        'currency'           => 'RWF',
        'timezone'           => 'Africa/Kigali',
        'phone_prefix'       => '+250',
        'national_id_label'  => 'National ID',
        'national_id_format' => 'digits_16',
        'grace_period_days'  => 2,
        'repayment_ratio'    => 0.3333,
        'crb_freshness_days' => 90,
        'kyc_freshness_days' => 90,
        'guarantor_required' => true,
        'contract_locale'    => 'en',
    ],
    'BI' => [
        'name'               => 'Burundi',
        'emoji'              => '🇧🇮',
        'active'             => false,
        'language'           => 'en',
        'currency'           => 'BIF',
        'timezone'           => 'Africa/Bujumbura',
        'phone_prefix'       => '+257',
        'national_id_label'  => 'National ID',
        'national_id_format' => 'alphanumeric',
        'grace_period_days'  => 2,
        'repayment_ratio'    => 0.3333,
        'crb_freshness_days' => 90,
        'kyc_freshness_days' => 90,
        'guarantor_required' => true,
        'contract_locale'    => 'en',
    ],
    'SS' => [
        'name'               => 'South Sudan',
        'emoji'              => '🇸🇸',
        'active'             => false,
        'language'           => 'en',
        'currency'           => 'SSP',
        'timezone'           => 'Africa/Juba',
        'phone_prefix'       => '+211',
        'national_id_label'  => 'National ID',
        'national_id_format' => 'alphanumeric',
        'grace_period_days'  => 2,
        'repayment_ratio'    => 0.3333,
        'crb_freshness_days' => 90,
        'kyc_freshness_days' => 90,
        'guarantor_required' => true,
        'contract_locale'    => 'en',
    ],
];
