<?php

return [
    'referral_levels' => [
        ['key' => 'bronze', 'label' => 'Bronze', 'min_referrals' => 0, 'max_referrals' => 5],
        ['key' => 'silver', 'label' => 'Silver', 'min_referrals' => 6, 'max_referrals' => 20],
        ['key' => 'gold', 'label' => 'Gold', 'min_referrals' => 21, 'max_referrals' => 50],
        ['key' => 'diamond', 'label' => 'Diamond', 'min_referrals' => 51, 'max_referrals' => null],
    ],

    'referral_level_benefits' => [
        'bronze'  => ['Reward points for successful invites', 'Referral progress tracking'],
        'silver'  => ['More reward points', 'Faster processing', 'Better interest rates'],
        'gold'    => ['Higher loan limits', 'Exclusive campaigns', 'Better interest rates'],
        'diamond' => ['Highest loan limits', 'Priority support', 'Exclusive campaigns'],
    ],

    'referral_milestones' => [
        ['target' => 5, 'reward_label' => 'Bonus reward points', 'reward_type' => 'bonus_points', 'reward_value' => 25],
    ],

    'trust_score' => [
        'max_stars' => 5,
        'weights' => [
            'on_time_payments'   => 30,
            'profile_completion' => 25,
            'referrals'          => 15,
            'account_age'        => 10,
            'successful_loans'   => 20,
        ],
        'benefits' => [
            'Higher loan limits',
            'Faster application processing',
        ],
    ],

    'community_milestones' => [
        ['key' => 'help_5_join', 'target' => 5, 'title' => 'Help 5 people join', 'rewards' => ['Bonus reward points', 'Cashback', 'Exclusive campaigns']],
    ],

    'repayment_streak' => [
        'enabled' => true,
        'reward_label' => 'Repayment streak points',
        'milestones' => [
            ['count' => 3, 'points' => 10],
            ['count' => 5, 'points' => 20],
            ['count' => 7, 'points' => 35],
            ['count' => 10, 'points' => 50],
            ['count' => 12, 'points' => 75],
        ],
    ],

    'profile_strength' => [
        ['key' => 'bronze', 'label' => 'Bronze', 'min_percent' => 0, 'max_percent' => 39],
        ['key' => 'silver', 'label' => 'Silver', 'min_percent' => 40, 'max_percent' => 69],
        ['key' => 'gold', 'label' => 'Gold', 'min_percent' => 70, 'max_percent' => 89],
        ['key' => 'verified', 'label' => 'Verified', 'min_percent' => 90, 'max_percent' => 100],
    ],

    'referral_wallet' => [
        /** TZS per 1 referral point shown to members (1 = 1 pt per TZS commission). */
        'points_per_tzs' => (int) env('REFERRAL_WALLET_POINTS_PER_TZS', 1),
    ],

    'loyalty_points' => [
        'stack_with_promo' => false,
        'actions' => [
            'complete_profile'  => ['label' => 'Complete profile / KYC', 'points' => 10],
            'refer_register'    => ['label' => 'Referred person registered', 'points' => 5],
            'refer_application' => ['label' => 'Referred person applied and paid the fee', 'points' => 25],
            'refer_friend'      => ['label' => 'Successful referral (legacy)', 'points' => 0],
            'repay_on_time'     => ['label' => 'Repay On Time', 'points' => 0],
            'upload_documents'  => ['label' => 'Upload Documents', 'points' => 0],
            'update_information'=> ['label' => 'Update Information', 'points' => 0],
            'plus_learn'        => ['label' => 'Complete selected Plus learning', 'points' => 5],
            'plus_money_checkin'=> ['label' => 'Complete a monthly Plus money check-in', 'points' => 5],
            'plus_goal'         => ['label' => 'Complete a Plus goal', 'points' => 10],
        ],
        'penalties' => [
            'late_repayment' => [
                'label'  => 'Late repayment',
                'points' => 50,
                'enabled'=> true,
            ],
            'late_fee_accrual' => [
                'label'  => 'Late fee charged',
                'points' => 25,
                'enabled'=> true,
            ],
        ],
        'redemptions' => [
            'membership_discount'   => 'Fee discounts',
            'interest_discount'     => 'Interest discounts',
            'processing_fee_discount'=> 'Processing fee discounts',
            'priority_support'      => 'Priority support',
            'merchandise'           => 'Merchandise',
        ],
        'redemption_options' => [
            [
                'key'           => 'application_fee_10',
                'label'         => '10% off application fee',
                'label_sw'      => 'Punguzo la 10% kwa ada ya maombi',
                'description'   => 'Unlock, then apply on your next application-fee payment.',
                'description_sw'=> 'Fungua, kisha tumia kwenye malipo yako ya ada ya maombi.',
                'points'        => 100,
                'benefit_type'  => 'percent_discount',
                'benefit_value' => 10,
                'fee_type'      => 'application_fee',
                'audience'      => 'everyone',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 90,
            ],
            [
                'key'           => 'application_fee_25',
                'label'         => '25% off application fee',
                'label_sw'      => 'Punguzo la 25% kwa ada ya maombi',
                'description'   => 'Unlock, then apply on your next application-fee payment.',
                'description_sw'=> 'Fungua, kisha tumia kwenye malipo yako ya ada ya maombi.',
                'points'        => 200,
                'benefit_type'  => 'percent_discount',
                'benefit_value' => 25,
                'fee_type'      => 'application_fee',
                'audience'      => 'everyone',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 90,
            ],
            [
                'key'           => 'application_fee_50',
                'label'         => '50% off application fee',
                'label_sw'      => 'Punguzo la 50% kwa ada ya maombi',
                'description'   => 'Unlock, then apply on your next application-fee payment.',
                'description_sw'=> 'Fungua, kisha tumia kwenye malipo yako ya ada ya maombi.',
                'points'        => 300,
                'benefit_type'  => 'percent_discount',
                'benefit_value' => 50,
                'fee_type'      => 'application_fee',
                'audience'      => 'everyone',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 90,
            ],
            [
                'key'           => 'application_fee_waive',
                'label'         => 'One application fee waived',
                'label_sw'      => 'Ada ya maombi imesamehewa mara moja',
                'description'   => 'Unlock, then apply to waive one application fee.',
                'description_sw'=> 'Fungua, kisha tumia kusamehe ada moja ya maombi.',
                'points'        => 500,
                'benefit_type'  => 'fee_waiver',
                'benefit_value' => 100,
                'fee_type'      => 'application_fee',
                'audience'      => 'everyone',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 90,
            ],
            [
                'key'           => 'plus_membership_10',
                'label'         => '10% off Kopafasta Plus',
                'label_sw'      => 'Punguzo la 10% kwa Kopafasta Plus',
                'description'   => 'Unlock, then apply on your Plus join or renew payment.',
                'description_sw'=> 'Fungua, kisha tumia kwenye malipo ya kujiunga au kufanya upya Plus.',
                'points'        => 250,
                'benefit_type'  => 'percent_discount',
                'benefit_value' => 10,
                'fee_type'      => 'kopafasta_plus',
                'audience'      => 'everyone',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 90,
            ],
            [
                'key'           => 'plus_membership_20',
                'label'         => '20% off Kopafasta Plus',
                'label_sw'      => 'Punguzo la 20% kwa Kopafasta Plus',
                'description'   => 'Unlock, then apply on your Plus join or renew payment.',
                'description_sw'=> 'Fungua, kisha tumia kwenye malipo ya kujiunga au kufanya upya Plus.',
                'points'        => 400,
                'benefit_type'  => 'percent_discount',
                'benefit_value' => 20,
                'fee_type'      => 'kopafasta_plus',
                'audience'      => 'everyone',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 90,
            ],
            [
                'key'           => 'priority_support',
                'label'         => 'Priority support (30 days)',
                'label_sw'      => 'Usaidizi wa kipaumbele (siku 30)',
                'description'   => 'Support tickets are marked and queued as priority while this is active.',
                'description_sw'=> 'Tiketia za msaada zinaonyeshwa na kuwekwa kwenye foleni ya kipaumbele.',
                'points'        => 150,
                'benefit_type'  => 'support_flag',
                'benefit_value' => 0,
                'fee_type'      => null,
                'audience'      => 'everyone',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 30,
            ],
            [
                'key'           => 'plus_application_fee_waive',
                'label'         => 'Plus: application-fee waiver',
                'label_sw'      => 'Plus: samehe ada ya maombi',
                'description'   => 'Plus members unlock a fee waiver for fewer points.',
                'description_sw'=> 'Wanachama wa Plus wanafungua samehe ya ada kwa pointi chache.',
                'points'        => 400,
                'benefit_type'  => 'fee_waiver',
                'benefit_value' => 100,
                'fee_type'      => 'application_fee',
                'audience'      => 'plus_only',
                'max_saving'    => null,
                'stackable'     => false,
                'expires_days'  => 90,
            ],
        ],
    ],

    'notifications' => [
        'categories' => ['repayment', 'application', 'promotions', 'referral', 'membership', 'group_loan'],
        'date_groups' => ['today', 'yesterday', 'earlier'],
    ],

    'leaderboard' => [
        'enabled' => true,
        'limit' => 10,
        'mask_names' => true,
    ],

    'underwriting_boosts' => [
        'referral_level' => [
            'bronze'  => ['limit_multiplier' => 1.00, 'rate_discount' => 0.000, 'processing_priority' => 0],
            'silver'  => ['limit_multiplier' => 1.05, 'rate_discount' => 0.005, 'processing_priority' => 1],
            'gold'    => ['limit_multiplier' => 1.10, 'rate_discount' => 0.010, 'processing_priority' => 2],
            'diamond' => ['limit_multiplier' => 1.15, 'rate_discount' => 0.015, 'processing_priority' => 3],
        ],
        'trust_score' => [
            'limit_multiplier_per_step'     => 0.02,
            'rate_discount_per_step'          => 0.002,
            'processing_priority_per_step'    => 0.5,
        ],
    ],
];
