<?php

return [
    'default' => [
        'icon'  => '💼',
        'theme' => 'slate',
        'illustration' => 'wallet',
        'label' => 'Loan product',
        'label_sw' => 'Bidhaa ya mkopo',
    ],
    'IL' => [
        'icon' => '🏠',
        'theme' => 'indigo',
        'label' => 'Individual Loan',
        'label_sw' => 'Mkopo wa mtu binafsi',
        'illustration' => 'individual',
    ],
    'SL' => [
        'icon' => '☪',
        'theme' => 'emerald',
        'label' => 'Sharia Loan',
        'label_sw' => 'Mkopo wa Sharia',
        'illustration' => 'individual',
    ],
    'GL' => [
        'icon' => '🤝',
        'theme' => 'violet',
        'label' => 'Group Loan',
        'label_sw' => 'Mkopo wa kikundi',
        'illustration' => 'group',
    ],
    'AL' => [
        'icon' => '🚗',
        'theme' => 'sky',
        'label' => 'Asset Lending',
        'label_sw' => 'Mkopo wa mali',
        'illustration' => 'vehicle',
    ],
    'AST' => [
        'icon' => '🚗',
        'theme' => 'sky',
        'label' => 'Asset Lending',
        'label_sw' => 'Mkopo wa mali',
        'illustration' => 'vehicle',
    ],
    'FC' => [
        'icon' => '🛠',
        'theme' => 'amber',
        'label' => 'Funding Capital',
        'label_sw' => 'Mtaji wa ufadhili',
        'illustration' => 'business',
    ],
    'KB' => [
        'icon' => '🚜',
        'theme' => 'emerald',
        'label' => 'Kilimo Boost',
        'label_sw' => 'Msukumo wa kilimo',
        'illustration' => 'agriculture',
    ],
    'BP' => [
        'icon' => '🏪',
        'theme' => 'orange',
        'label' => 'Biashara Plus',
        'label_sw' => 'Biashara Plus',
        'illustration' => 'business',
    ],
    'EL' => [
        'icon' => '🎓',
        'theme' => 'blue',
        'label' => 'Education Loan',
        'label_sw' => 'Mkopo wa elimu',
        'illustration' => 'education',
    ],
    'EM' => [
        'icon' => '🚑',
        'theme' => 'rose',
        'label' => 'Emergency Loan',
        'label_sw' => 'Mkopo wa dharura',
        'illustration' => 'emergency',
    ],
    'WL' => [
        'icon' => '👩',
        'theme' => 'pink',
        'label' => 'Women Loan',
        'label_sw' => 'Mkopo wa wanawake',
        'illustration' => 'women',
    ],
    'AB' => [
        'icon' => '🏗',
        'theme' => 'cyan',
        'label' => 'Asset / Business',
        'label_sw' => 'Mali / Biashara',
        'illustration' => 'business',
    ],
];
