<?php

/**
 * Canonical role definitions for KopaFasta.
 *
 * @see docs/ACL-WORKFLOW.md
 */
return [
    'definitions' => [
        'admin' => [
            'label'              => 'Administrator',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => true,
            'policy_bypass'      => true,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => null,
            'duty'               => 'Full console. Can enroll partners, assign desks, and hold any team combination.',
            'api_capabilities'   => ['core', 'reports', 'system', 'security', 'collections', 'support', 'audit'],
        ],
        'super_admin' => [
            'label'              => 'Super administrator',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => null,
            'duty'               => 'Full console access. Branch policies still apply.',
            'api_capabilities'   => ['core', 'reports', 'system', 'collections', 'support', 'audit'],
        ],
        'manager' => [
            'label'              => 'Credit manager',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => 'CRM',
            'duty'               => 'After committee approval: offer, fees, contract, and disbursement. Does not sit on Screening and Committee at once.',
            'api_capabilities'   => ['core', 'reports', 'system', 'collections', 'support'],
        ],
        'officer' => [
            'label'              => 'Loan officer',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => 'UND',
            'duty'               => 'Screens loan files (documents, face, affordability). Does not enroll partners or sit on Committee.',
            'api_capabilities'   => ['core', 'reports'],
        ],
        'collector' => [
            'label'              => 'Collector',
            'console_access'     => false,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => false,
            'users_filter'       => false,
            'api_capabilities'   => ['collections'],
        ],
        'credit_analyst' => [
            'label'              => 'Credit analyst',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => 'UND',
            'duty'               => 'Screens and appraises applications before committee. Does not enroll partners or sit on Committee.',
            'api_capabilities'   => ['core', 'reports'],
        ],
        'credit_committee' => [
            'label'              => 'Credit committee',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => 'CRC',
            'duty'               => 'Approves, counters, or rejects. Committee already owns the credit decision — no per-person approval limit.',
            'api_capabilities'   => ['core', 'reports'],
        ],
        'agent' => [
            'label'              => 'Support agent',
            'console_access'     => false,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => false,
            'users_filter'       => false,
            'api_capabilities'   => ['support'],
        ],
        'auditor' => [
            'label'              => 'Auditor',
            'console_access'     => false,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => false,
            'users_filter'       => true,
            'api_capabilities'   => ['audit'],
        ],
        'asset_manager' => [
            'label'              => 'Asset manager',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => 'OPS',
            'duty'               => 'Manages marketplace listings and borrower asset requests.',
            'api_capabilities'   => [],
        ],
        'partner_support' => [
            'label'              => 'Partner support',
            'console_access'     => true,
            'staff'              => true,
            'permission_bypass'  => false,
            'policy_bypass'      => false,
            'user_form'          => true,
            'users_filter'       => true,
            'desk'               => 'PRT',
            'duty'               => 'Screens partner applications, enrolls partners, adds regional coverage, and activates portal access. Does not screen or decide loans.',
            'api_capabilities'   => ['core'],
        ],
        'borrower' => [
            'label'              => 'Borrower',
            'console_access'     => false,
            'staff'              => false,
            'portal'             => 'borrower',
        ],
        'customer' => [
            'label'              => 'Customer',
            'console_access'     => false,
            'staff'              => false,
            'portal'             => 'borrower',
        ],
        'vendor' => [
            'label'              => 'Vendor',
            'console_access'     => false,
            'staff'              => false,
            'portal'             => 'vendor',
        ],
        'investor' => [
            'label'              => 'Investor',
            'console_access'     => false,
            'staff'              => false,
            'portal'             => 'investor',
        ],
    ],

    /** Maps capability tokens used in API middleware to role codes. */
    'api_capabilities' => [
        'core'        => ['officer', 'manager', 'admin', 'super_admin', 'credit_analyst', 'partner_support'],
        'collections' => ['officer', 'manager', 'admin', 'super_admin', 'collector'],
        'reports'     => ['officer', 'manager', 'admin', 'super_admin'],
        'system'      => ['manager', 'admin', 'super_admin'],
        'security'    => ['admin'],
        'support'     => ['agent', 'manager', 'admin', 'super_admin'],
        'audit'       => ['auditor', 'admin', 'super_admin'],
        'portal'      => ['customer', 'borrower'],
    ],
];
