<x-site.layout title="Privacy Policy — Kopafasta">
    <article class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 prose prose-slate max-w-none">
        <p class="text-xs uppercase tracking-widest text-brand font-semibold mb-2"><a href="{{ route('site.legal') }}" class="hover:underline">Legal</a> · Privacy</p>
        <h1 class="text-3xl font-bold text-gray-900 !mb-2">Privacy Policy</h1>
        <p class="text-sm text-gray-500 !mt-0">Effective {{ date('d F Y') }}. This Policy explains how {{ brand('legal_name') }} (“Kopafasta”, “we”, “us”) processes personal data for microfinance membership, lending, payments, and related services in line with common international data-protection principles and applicable Tanzania / East Africa requirements.</p>

        <h2>1. Who we are</h2>
        <p>We are the data controller for borrower and member accounts on the Kopafasta platform. Contact: <a href="mailto:{{ brand('support_email') }}">{{ brand('support_email') }}</a>.</p>

        <h2>2. Personal data we collect</h2>
        <ul>
            <li><strong>Identity &amp; contact:</strong> name, date of birth, gender, phone, email, national ID / NIDA, photos and face verification captures, address and residence proofs.</li>
            <li><strong>Financial &amp; credit:</strong> income, employment/business details, bank or mobile money identifiers, loan applications, repayment history, collateral and insurance data, CRB / bureau reports, guarantor and group-member links.</li>
            <li><strong>Transaction:</strong> payment references, PSP tokens/refs, amounts, timestamps, channel (mobile money / bank), device and IP used for security.</li>
            <li><strong>Usage &amp; support:</strong> portal activity, notification preferences, support chats, and authorised partner call notes.</li>
            <li><strong>Marketing (optional):</strong> campaign engagement where you opt in or as allowed by local law.</li>
        </ul>

        <h2>3. Sources</h2>
        <p>We collect data you provide; data generated by your use of the platform; and data from licensed third parties you authorise or that law permits (identity providers, credit bureaus, PSPs, valuers, GPS/insurance partners, and referral/affiliate partners).</p>

        <h2>4. Purposes and legal bases</h2>
        <ul>
            <li>Create, secure, and administer your account (contract / legitimate interest).</li>
            <li>Assess creditworthiness, affordability, and fraud/AML risk (legal obligation / legitimate interest / consent where required).</li>
            <li>Price, disburse, collect, and service loans and membership (contract).</li>
            <li>Send transactional SMS/email (OTP, USSD payment prompts, membership reminders, arrears notices) (contract / legitimate interest).</li>
            <li>Improve product safety and service quality using aggregated or de-identified analytics (legitimate interest).</li>
            <li>Marketing communications only with opt-in or as otherwise permitted; you may opt out of marketing without affecting transactional messages.</li>
        </ul>

        <h2>5. Sharing</h2>
        <p>We share personal data with: payment service providers; credit bureaus; identity and face-verification providers; valuers, GPS, insurance, yard, and collection partners engaged on your loan; regulators, courts, and law enforcement when required; and cloud/infrastructure vendors under confidentiality and security terms. We do not sell personal data.</p>

        <h2>6. International transfers</h2>
        <p>Where vendors process data outside Tanzania, we use contractual and organisational safeguards consistent with applicable data-protection law.</p>

        <h2>7. Retention</h2>
        <p>We retain account and loan records for as long as needed for the relationship and for statutory financial-crime, tax, and audit retention (often several years after account closure), then delete or anonymise where feasible.</p>

        <h2>8. Security</h2>
        <p>We apply access controls, encryption in transit, PIN/password protections, staff/partner confidentiality, and monitoring for abuse. No method is 100% secure — protect your PIN and devices and report suspected compromise promptly.</p>

        <h2>9. Your rights</h2>
        <p>Subject to local law, you may request access, correction, deletion, restriction, or objection, and withdraw consent where processing is consent-based. Use Support in the app or email us. You may also lodge a complaint with the competent data-protection authority. Some rights are limited where we must keep records for lending, AML, or legal claims.</p>

        <h2>10. Automated decisions</h2>
        <p>Credit scoring and eligibility checks may involve automated elements. Where law requires, you may request human review of a decision that produces legal or similarly significant effects.</p>

        <h2>11. Children</h2>
        <p>Our services are not directed to anyone under 18. We do not knowingly create borrower memberships for minors.</p>

        <h2>12. Cookies and similar technologies</h2>
        <p>Our website may use essential cookies for session security and preferences (language/country), and limited analytics cookies. You can control non-essential cookies via your browser settings.</p>

        <h2>13. Changes</h2>
        <p>We may update this Policy and will post the revised version with a new effective date. Material changes affecting your rights will be highlighted where practical.</p>

        <p class="text-sm text-gray-500"><a href="{{ route('site.legal.terms') }}" class="text-brand font-semibold hover:underline">Terms of Service →</a>
            · <a href="{{ route('site.legal') }}" class="text-brand font-semibold hover:underline">All documents</a></p>
    </article>
</x-site.layout>
